import type { Metadata } from "next";
// import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Nav from "./nav";
import Container from "react-bootstrap/Container";

export const metadata: Metadata = {
  title: "Lorawan Sensor Dashboard",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <main>
          <Container className="pt-sm-5 pb-5">
            {children}
          </Container>
        </main>
      </body>
    </html>
  );
}
