import type { Metadata } from "next";
import "./globals.css";
import Nav from "./nav";

export const metadata: Metadata = {
  title: "Lorawan Sensor Dashboard",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-full flex-col p-10 bg-background">
          <Nav />
          <main className="mt-5">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
